// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Label$ReactHooksTemplate = require("./Label.bs.js");

function getValue(e) {
  return e.target.value;
}

function updateFormState(state, field, value) {
  switch (field) {
    case 0 : 
        return /* record */[
                /* income */value,
                /* spending */state[/* spending */1],
                /* years */state[/* years */2]
              ];
    case 1 : 
        return /* record */[
                /* income */state[/* income */0],
                /* spending */value,
                /* years */state[/* years */2]
              ];
    case 2 : 
        return /* record */[
                /* income */state[/* income */0],
                /* spending */state[/* spending */1],
                /* years */value
              ];
    
  }
}

function Calc(Props) {
  var match = React.useReducer((function (state, action) {
          return updateFormState(state, action[0], action[1]);
        }), /* record */[
        /* income */"0",
        /* spending */"0",
        /* years */"0"
      ]);
  var dispatch = match[1];
  var state = match[0];
  return React.createElement("form", undefined, "FIRE Calculator", React.createElement(Label$ReactHooksTemplate.make, {
                  children: null
                }, "Income", React.createElement("input", {
                      value: state[/* income */0],
                      onChange: (function (e) {
                          var value = e.target.value;
                          return Curry._1(dispatch, /* InputChange */[
                                      /* Income */0,
                                      value
                                    ]);
                        })
                    })), React.createElement(Label$ReactHooksTemplate.make, {
                  children: null
                }, "Spending", React.createElement("input", {
                      value: state[/* spending */1],
                      onChange: (function (e) {
                          var value = e.target.value;
                          return Curry._1(dispatch, /* InputChange */[
                                      /* Spending */1,
                                      value
                                    ]);
                        })
                    })), React.createElement(Label$ReactHooksTemplate.make, {
                  children: null
                }, "Years", React.createElement("input", {
                      value: state[/* years */2],
                      onChange: (function (e) {
                          var value = e.target.value;
                          return Curry._1(dispatch, /* InputChange */[
                                      /* Years */2,
                                      value
                                    ]);
                        })
                    })), React.createElement("button", undefined, "Calculate"));
}

var make = Calc;

exports.getValue = getValue;
exports.updateFormState = updateFormState;
exports.make = make;
/* react Not a pure module */
