// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Caml_format = require("bs-platform/lib/js/caml_format.js");
var Finance$ReactHooksTemplate = require("./Finance.bs.js");

function reducer(param, action) {
  var formValues = action[0];
  var yearlySavings = Finance$ReactHooksTemplate.savings(Caml_format.caml_float_of_string(formValues[/* income */2]), Caml_format.caml_float_of_string(formValues[/* spending */3]));
  var resultList = Finance$ReactHooksTemplate.getResultList(Caml_format.caml_float_of_string(formValues[/* annualReturn */0]), Caml_format.caml_float_of_string(formValues[/* currBalance */1]), yearlySavings);
  var targetAmount = Caml_format.caml_float_of_string(formValues[/* spending */3]) * 25.0;
  var targetYear = Finance$ReactHooksTemplate.getFIREYear(resultList, targetAmount);
  return /* record */[
          /* resultList */resultList,
          /* targetAmount */targetAmount,
          /* targetYear */targetYear
        ];
}

var Data_000 = /* initialState : record */[
  /* resultList : [] */0,
  /* targetAmount */0.0,
  /* targetYear */undefined
];

var Data = /* module */[
  Data_000,
  /* magicConstant */25.0,
  /* reducer */reducer
];

exports.Data = Data;
/* No side effect */
