// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function getResultList(rate, principal, yearlySavings) {
  var yearsArray = Belt_Array.range(1, 25);
  var calculate = function (prevValue) {
    return Math.round((prevValue + yearlySavings) * (1.0 + rate / 100.0 / 1.0));
  };
  return $$Array.fold_left((function (acc, year) {
                var index = List.length(acc) - 1 | 0;
                var match = index >= 0;
                var prevValue = match ? List.nth(acc, index)[/* netWorth */1] : principal;
                var netWorth = calculate(prevValue);
                var roi = netWorth - yearlySavings - prevValue;
                var changeInNetWorth = netWorth - prevValue;
                var result = /* record */[
                  /* year */year,
                  /* netWorth */netWorth,
                  /* changeInNetWorth */changeInNetWorth,
                  /* roi */roi
                ];
                return List.append(acc, /* :: */[
                            result,
                            /* [] */0
                          ]);
              }), /* [] */0, yearsArray);
}

function getFIREYear(amounts, targetAmount) {
  var amountsLength = List.length(amounts) - 1 | 0;
  var _$staropt$star = 0;
  while(true) {
    var $staropt$star = _$staropt$star;
    var index = $staropt$star !== undefined ? $staropt$star : 0;
    if (amountsLength === index) {
      return undefined;
    } else if (List.nth(amounts, index)[/* netWorth */1] >= targetAmount) {
      return index + 1 | 0;
    } else {
      _$staropt$star = index + 1 | 0;
      continue ;
    }
  };
}

function getSavingsRate(income, spending) {
  return Math.floor((income - spending) / income * 100.0);
}

function getSpendingBySavings(income, savingsRate) {
  return Math.floor(income - income * savingsRate / 100.0);
}

exports.getResultList = getResultList;
exports.getFIREYear = getFIREYear;
exports.getSavingsRate = getSavingsRate;
exports.getSpendingBySavings = getSpendingBySavings;
/* No side effect */
