// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function compoundInterest(rate, principal, yearlySavings) {
  var yearsArray = Belt_List.fromArray(Belt_Array.range(1, 25));
  var calculate = function (prevValue) {
    return Math.round((prevValue + yearlySavings) * (1.0 + rate / 100.0 / 1.0));
  };
  return List.fold_left((function (acc, year) {
                var index = List.length(acc) - 1 | 0;
                var match = index >= 0;
                var prevValue = match ? List.nth(acc, index) : principal;
                return List.append(acc, /* :: */[
                            calculate(prevValue),
                            /* [] */0
                          ]);
              }), /* [] */0, yearsArray);
}

function getFIREYear(amounts, targetAmount, index) {
  return 2;
}

function savings(income, spending) {
  return income - spending;
}

function savingsRate(income, spending) {
  return Math.round((income - spending) / income * 100.0);
}

exports.compoundInterest = compoundInterest;
exports.getFIREYear = getFIREYear;
exports.savings = savings;
exports.savingsRate = savingsRate;
/* No side effect */
