// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function compoundInterest(rate, principal, yearlySavings) {
  var yearsArray = Belt_Array.range(1, 25);
  var calculate = function (prevValue) {
    return Math.round((prevValue + yearlySavings) * (1.0 + rate / 100.0 / 1.0));
  };
  return $$Array.fold_left((function (acc, year) {
                var index = acc.length - 1 | 0;
                var match = index >= 0;
                var maybePrevVal = match ? Caml_array.caml_array_get(acc, acc.length - 1 | 0) : undefined;
                var prevValue = maybePrevVal !== undefined ? maybePrevVal : principal;
                return $$Array.append(acc, /* array */[calculate(prevValue)]);
              }), /* array */[], yearsArray);
}

function savings(income, spending) {
  return income - spending;
}

function savingsRate(income, spending) {
  return Math.round((income - spending) / income * 100.0);
}

exports.compoundInterest = compoundInterest;
exports.savings = savings;
exports.savingsRate = savingsRate;
/* No side effect */
