// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

var format = ( new Intl.NumberFormat(undefined).format );

function FormattedCurrency(Props) {
  var value = Props.value;
  return React.createElement(React.Fragment, undefined, Curry._1(format, value));
}

var make = FormattedCurrency;

exports.format = format;
exports.make = make;
/* format Not a pure module */
