// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

var style = {
  display: "block",
  margin: "2rem 0"
};

function Label(Props) {
  var children = Props.children;
  return React.createElement("label", {
              style: style
            }, children);
}

var make = Label;

exports.style = style;
exports.make = make;
/* react Not a pure module */
