// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var FormattedCurrency$ReactHooksTemplate = require("./FormattedCurrency.bs.js");

function Table(Props) {
  var annualReturn = Props.annualReturn;
  var data = Props.data;
  return React.createElement("section", {
              className: "section"
            }, React.createElement("div", {
                  className: "box"
                }, React.createElement("div", {
                      className: "columns"
                    }, React.createElement("div", {
                          className: "column"
                        }, "End of year"), React.createElement("div", {
                          className: "column"
                        }, "Net worth"), React.createElement("div", {
                          className: "column"
                        }, "Change in net worth"), React.createElement("div", {
                          className: "column"
                        }, "ROI (" + (annualReturn + "%)"))), $$Array.of_list(List.map((function (param) {
                            return React.createElement("div", {
                                        className: "columns"
                                      }, React.createElement("div", {
                                            className: "column"
                                          }, String(param[/* year */0])), React.createElement("div", {
                                            className: "column"
                                          }, React.createElement(FormattedCurrency$ReactHooksTemplate.make, {
                                                value: param[/* netWorth */1]
                                              })), React.createElement("div", {
                                            className: "column"
                                          }, React.createElement(FormattedCurrency$ReactHooksTemplate.make, {
                                                value: param[/* changeInNetWorth */2]
                                              })), React.createElement("div", {
                                            className: "column"
                                          }, React.createElement(FormattedCurrency$ReactHooksTemplate.make, {
                                                value: param[/* roi */3]
                                              })));
                          }), data))));
}

var make = Table;

exports.make = make;
/* react Not a pure module */
