// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var FormattedCurrency$ReactHooksTemplate = require("./FormattedCurrency.bs.js");

function Table(Props) {
  var data = Props.data;
  return React.createElement("section", {
              className: "section"
            }, React.createElement("div", {
                  className: "box"
                }, React.createElement("div", {
                      className: "columns"
                    }, React.createElement("div", {
                          className: "column"
                        }, "Years"), React.createElement("div", {
                          className: "column"
                        }, "Amount")), $$Array.of_list(Belt_List.mapWithIndex(data, (function (index, amount) {
                            return React.createElement("div", {
                                        className: "columns"
                                      }, React.createElement("div", {
                                            className: "column"
                                          }, String(index + 1 | 0)), React.createElement("div", {
                                            className: "column"
                                          }, React.createElement(FormattedCurrency$ReactHooksTemplate.make, {
                                                value: amount
                                              })));
                          })))));
}

var make = Table;

exports.make = make;
/* react Not a pure module */
